import product1 from "../../assets/products/product1.jfif";
import product2 from "../../assets/products/product2.webp";
import product3 from "../../assets/products/product3.jpg";
import product4 from "../../assets/products/product4.jpg";

export const allProducts = [
  {
    id: "#001",
    name: "Black Cotton",
    category: "italian-boski-flat-50-off",
    price: 1000,
    image1: product1,
    discount: 20,
    saleQuantity: 50,
    isSale: true,
    inStock: 12,
    description:
      "A classic white cotton shirt that's perfect for any occasion. Made from 100% breathable cotton, it offers comfort and style in one package.",
    season: "Summer",
    material: "Cotton",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#002",
    name: "White Cotton",
    category: "italian-boski-flat-50-off",
    price: 1500,
    image1: product2,
    discount: 15,
    saleQuantity: 30,
    isSale: true,
    inStock: 0,
    description:
      "Stylish blue jeans that offer a perfect fit and comfort for all-day wear.",
    season: "All Seasons",
    material: "Denim",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#003",
    name: "Gray Cotton",
    category: "premium-paper-cotton-flat-50-off",
    price: 2200,
    image1: product3,
    discount: 25,
    saleQuantity: 46,
    inStock: 12,
    description:
      "A vibrant red t-shirt that's both comfortable and fashionable.",
    season: "Summer",
    material: "Cotton",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#004",
    name: "Blue Cotton",
    category: "premium-paper-cotton-flat-50-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 120,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#005",
    name: "Blue Cotton",
    category: "rafale-wool-falt-50-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#006",
    name: "Blue Cotton",
    category: "rafale-wool-falt-50-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#007",
    name: "Blue Cotton",
    category: "asal-double-ghora-boski-33-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#008",
    name: "Blue Cotton",
    category: "asal-double-ghora-boski-33-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#009",
    name: "Blue Cotton",
    category: "premium-royal-boski-50-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#010",
    name: "Blue Cotton",
    category: "premium-royal-boski-50-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#011",
    name: "Blue Cotton",
    category: "universal-wool-flat-43-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#012",
    name: "Blue Cotton",
    category: "universal-wool-flat-43-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#013",
    name: "Blue Cotton",
    category: "universal-wool-flat-43-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 0,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "#014",
    name: "Blue Cotton",
    category: "cross-hill-flat-39",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
];
