import product1 from "../../assets/products/product1.jfif";
import product2 from "../../assets/products/product2.webp";
import product3 from "../../assets/products/product3.jpg";
import product4 from "../../assets/products/product4.jpg";

export const allProducts = [
  {
    id: "1",
    name: "Black Cotton",
    category: "italian-boski-flat-50-off",
    price: 1000,
    image1: product1,
    discount: 20,
    saleQuantity: 50,
    isSale: true,
    inStock: 12,
    description:
      "A classic white cotton shirt that's perfect for any occasion. Made from 100% breathable cotton, it offers comfort and style in one package.",
    season: "Summer",
    material: "Cotton",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "2",
    name: "White Cotton",
    category: "italian-boski-flat-50-off",
    price: 1500,
    image1: product2,
    discount: 15,
    saleQuantity: 30,
    isSale: true,
    inStock: 0,
    description:
      "Stylish blue jeans that offer a perfect fit and comfort for all-day wear.",
    season: "All Seasons",
    material: "Denim",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "3",
    name: "Gray Cotton",
    category: "premium-paper-cotton-flat-50-off",
    price: 2200,
    image1: product3,
    discount: 25,
    saleQuantity: 46,
    inStock: 12,
    description:
      "A vibrant red t-shirt that's both comfortable and fashionable.",
    season: "Summer",
    material: "Cotton",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "4",
    name: "Blue Cotton",
    category: "premium-paper-cotton-flat-50-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 120,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "5",
    name: "Blue Cotton",
    category: "rafale-wool-falt-50-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "6",
    name: "Blue Cotton",
    category: "rafale-wool-falt-50-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "7",
    name: "Blue Cotton",
    category: "asal-double-ghora-boski-33-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "8",
    name: "Blue Cotton",
    category: "asal-double-ghora-boski-33-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "9",
    name: "Blue Cotton",
    category: "premium-royal-boski-50-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "10",
    name: "Blue Cotton",
    category: "premium-royal-boski-50-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "11",
    name: "Blue Cotton",
    category: "universal-wool-flat-43-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "12",
    name: "Blue Cotton",
    category: "universal-wool-flat-43-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "13",
    name: "Blue Cotton",
    category: "universal-wool-flat-43-off",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 0,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
  {
    id: "14",
    name: "Blue Cotton",
    category: "cross-hill-flat-39",
    price: 3200,
    image1: product4,
    discount: 10,
    saleQuantity: 20,
    inStock: 5,
    description:
      "A sleek black jacket that's perfect for adding a touch of sophistication to any outfit.",
    season: "Winter",
    material: "Wool",
    length: "4 Yards",
    width: "45 Inches",
  },
];

export const orders = [
  {
    id: "ORD-001",
    customer: {
      name: "Ali Muhammad",
      phone: "03001234567",
      email: "ali@example.com",
      address: "Gulshan-e-Iqbal, Karachi",
      city: "Karachi",
    },
    products: [
      {
        id: "P001",
        image: product1,
        name: "Shirt",
        price: 1000,
        qty: 2,
      },
      {
        id: "P002",
        image: product2,
        name: "Jeans",
        price: 1500,
        qty: 1,
      },
    ],

    total: 2500,
    status: "Completed",
    date: "2026-04-05",
  },
  {
    id: "ORD-002",
    customer: {
      name: "Sameer Qazi",
      phone: "03001234567",
      email: "sameer@example.com",
      address: "Gulshan-e-Iqbal, Peshawar",
      city: "Peshawar",
    },
    items: [
      { name: "Shirt", qty: 2 },
      { name: "Jeans", qty: 1 },
    ],
    products: [
      {
        id: "P001",
        image: product1,
        name: "Shirt",
        price: 1000,
        qty: 2,
      },
      {
        id: "P002",
        image: product2,
        name: "Jeans",
        price: 1500,
        qty: 1,
      },
    ],

    total: 2500,
    status: "Cancelled",
    date: "2026-04-05",
  },
  {
    id: "ORD-003",
    customer: {
      name: "Samavia Qazi",
      phone: "03001234567",
      email: "samavia@example.com",
      address: "Sheikh Muhammadi, Peshawar",
      city: "Peshawar",
    },
    items: [
      { name: "Shirt", qty: 2 },
      { name: "Jeans", qty: 1 },
    ],
    products: [
      {
        id: "P001",
        image: product1,
        name: "Shirt",
        price: 1000,
        qty: 2,
      },
      {
        id: "P002",
        image: product2,
        name: "Jeans",
        price: 1500,
        qty: 1,
      },
    ],

    total: 2500,
    status: "Pending",
    date: "2026-04-05",
  },
];

// Categories
export const category = [
  {
    id: "CAT-001",
    name: "Men Shirts",
    slug: "men-shirts",
    status: "Active",
    productCount: 12,
  },
  {
    id: "CAT-002",
    name: "Men Jeans",
    slug: "men-jeans",
    status: "Active",
    productCount: 15,
  },
  {
    id: "CAT-003",
    name: "Men Cap",
    slug: "men-cap",
    status: "Hidden",
    productCount: 0,
  },
];


// Customers 
export const customers = [
{
  id: "CUS-001",
  name: "Ali Muhammad",
  phone: "03001234567",
  email: "ali@example.com",
  city: "Karachi",
  address: "Gulshan-e-Iqbal",
  avatar: "/avatar.jpg",
  orders: 5,
  status: "Active"
}
];
